# Generated by Django 5.2 on 2026-09-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_translate_remaining_blog_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
